// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mathExpression;

#nullable disable

namespace mathExpression.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250117073858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mathExpression.Model.MathExpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MathExpressions");
                });

            modelBuilder.Entity("mathExpression.Model.MathExpressionSensor", b =>
                {
                    b.Property<int>("MathExpressionId")
                        .HasColumnType("int");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("MathExpressionId", "SensorId");

                    b.HasIndex("SensorId");

                    b.ToTable("MathExpressionSensors");
                });

            modelBuilder.Entity("mathExpression.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sensor1",
                            Value = 42.5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sensor2",
                            Value = 101.3m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sensor3",
                            Value = 55.7m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sensor4",
                            Value = 76m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sensor5",
                            Value = 89.9m
                        });
                });

            modelBuilder.Entity("mathExpression.Model.MathExpressionSensor", b =>
                {
                    b.HasOne("mathExpression.Model.MathExpression", "MathExpression")
                        .WithMany("MathExpressionSensors")
                        .HasForeignKey("MathExpressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mathExpression.Model.Sensor", "Sensor")
                        .WithMany("MathExpressionSensors")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MathExpression");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("mathExpression.Model.MathExpression", b =>
                {
                    b.Navigation("MathExpressionSensors");
                });

            modelBuilder.Entity("mathExpression.Model.Sensor", b =>
                {
                    b.Navigation("MathExpressionSensors");
                });
#pragma warning restore 612, 618
        }
    }
}
